name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install
      working-directory: services/todo_api
    
    - name: Run isort
      run: poetry run isort --profile black . --check
      working-directory: services/todo_api

    - name: Run black
      run: poetry run black . --check
      working-directory: services/todo_api
    
    - name: Run flake8
      run: poetry run flake8 .
      working-directory: services/todo_api
    
    - name: Run bandit
      run: poetry run bandit -r .
      working-directory: services/todo_api